version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  job_finder:
    image: job_finder
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 4000:4000